### PR TITLE
Added support for the contains query operator

### LINKED ISSUE #10: It does not support 'contains' keyword in findAll() query
I tried

```
User.findAll({tags: {"contains": "a"}}).then(..)
```

But got

```
error ReqlDriverError {message: "Annonymous function returned `undefined`. Did you forget a `return`?"}
```

It works in filter() though. So it seems the adapter does not support "contains" keyword?

### PR DESCRIPTION
**Pull request by recipher**
This should fix #10.

I've made the query case-insensitive. I guess it would be better for this to be an option, but I couldn't see a reasonable way to do that.

Thanks.

### CODE REVIEW

**Comment by jmdobry** [comment]
The "contains" operator needs to work for arrays as well (see how it's implemented in [js-data.js](https://github.com/js-data/js-data/blob/master/src/datastore/index.js#L217) ). Also, can you remove your changes to `dist/js-data-rethinkdb.js` from the PR?

**Comment by recipher** [comment]
Just to be clear, when you say it should work with arrays, do you mean

1. Check an array property to see if any of the elements in the array contains the string term?

2. Check to see if a string property contains any of the elements in an array term?

I'll need to investigate ReQL to check to see if this is possible. The contains operator in ReQL needs to work in conjunction with the match operator, it seems to me.

http://rethinkdb.com/api/javascript/contains/

I'll close this and create another, without the changes to `dist`.

**Comment by recipher** [comment]
Looking at http://www.js-data.io/docs/query-syntax

It seems like option 1 is the requirement.

```
// Get all users where user.roles contains "admin"
User.filter({
  where: {
    roles: {
      'contains': 'admin'
    }
  }
});
```

Is there a simple way to tell whether `roles` (in the example above), is an array property or a string property, since I'll use ReQL operator match for strings and operator contains for arrays.

**Comment by jmdobry** [comment]
I'm not for sure on how to implement it, which is why I didn't implement it in the first place.

**Comment by recipher** [comment]
Ah, ok. It's not worth implementing it for at least the first case (string matching) then? And then add the second case later?

Under normal circumstances, I'd expect these to be 2 different operations (as they are in MongoDB and RethinkDB). In any NoSQL DB, since a column can have any "type", it might prove problematic to determine which type a column is.

Might it make more sense (and more work) to split them into 2 separate ops:

```
// Get all users where user.roles contains "admin"
User.filter({
  where: {
    roles: {
      'contains': 'admin'
    }
  }
});
```

And

```
// Get all users where user.roles contains "admin"
User.filter({
  where: {
    name: {
      'like': 'john'
    }
  }
});
```

**Comment by jmdobry** [comment]
I'll have to think about it some more. js-data-sql actually has a "like" operator. I want consistency across the store and the adapters.

**Comment by recipher** [comment]
Grand. Thanks.



—
Johnny H
07971 880871

**Pull request closed without merging**
